# Generated by Django 3.1.1 on 2020-10-04 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssesmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('assesment_category', models.CharField(choices=[('HW', 'Homework'), ('CW', 'Classwork')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('correct_answer', models.BooleanField()),
                ('feedback', models.CharField(max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.assesmentitem')),
            ],
        ),
    ]
